// Generated by CoffeeScript 1.7.1
(function() {
  window.main = {
    init: function() {
      setTimeout(function() {
        return $("html").addClass("init");
      }, 10);
      setTimeout(function() {
        return $("html").addClass("init-1");
      }, 200);
      setTimeout(function() {
        return $("html").addClass("init-2");
      }, 700);
      return main.actions();
    },
    actions: function() {
      return $(".login_fb").click(function(e) {
        e.preventDefault();
        main.loginFb();
      });
    },
    loginFb: function() {
      var cbFB;
      if (Modernizr.Detectizr.device.type === "desktop") {
        return FB.getLoginStatus(function(response) {
          var access_token;
          if (response.status === "connected") {
            access_token = response.authResponse.accessToken;
            return FB.api("/me", function(response) {
              return main.userLogin(response, access_token);
            });
          } else {
            return FB.login((function(response) {
              if (response.authResponse) {
                access_token = FB.getAuthResponse()["accessToken"];
                return FB.api("/me", function(response) {
                  return main.userLogin(response, access_token);
                });
              }
            }), {
              scope: "email,publish_stream"
            });
          }
        });
      } else {
        cbFB = APP_URI + "usuarios/callback";
        return location.href = 'https://www.facebook.com/dialog/oauth?client_id=' + clientId + '&redirect_uri=' + cbFB + '&scope=email,publish_actions&state=' + Math.floor(Math.random() * 11);
      }
    },
    userLogin: function(user, token) {
      if (user.id !== void 0 && user.email !== void 0 && user.first_name !== void 0) {
        return $.ajax({
          url: APP_URI + "/facebook/login",
          type: "POST",
          data: "email=" + user.email + "&first_name=" + user.first_name + "&gender=" + user.gender + "&id=" + user.id + "&last_name=" + user.last_name + "&link=" + user.link + "&locale=" + user.locale + "&name=" + user.name + "&timezone=" + user.timezone + "&updated_time=" + user.updated_time + "&username=" + user.username + "&access_token=" + token,
          dataType: "json",
          beforeSend: function() {},
          success: function(results) {
            if (results.state === 1 || results.state === 2) {
              return location.href = APP_URI + '?login=ok';
            } else {
              return alert("error al guardar");
            }
          }
        });
      } else {
        return main.loginFb();
      }
    }
  };

  $('document').ready(function() {
    return window.main.init();
  });

}).call(this);

//# sourceMappingURL=scripts.map
